permissions:
  contents: read

name: ci workflow
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["22.13.0", "24"]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.26.1

      - name: 🪢 Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "./pnpm-lock.yaml"
          cache: "pnpm"

      - name: 🛒 Install
        run: pnpm install --frozen-lockfile

      - name: 🔬 Lint
        run: pnpm lint

      - name: 🔧 Build
        run: pnpm build
