permissions:
  contents: read

name: E2E

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  GAMEMAKER_AUTH_TOKEN: ${{ secrets.GAMEMAKER_AUTH_TOKEN }}

jobs:
  e2e:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-latest
            shell: bash
          - runner: ubuntu-latest
            shell: bash
          - runner: windows-latest
            shell: pwsh

    runs-on: ${{ matrix.runner }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.26.1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache-dependency-path: "./pnpm-lock.yaml"
          cache: "pnpm"

      - name: Prep
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: E2E (Bash)
        if: runner.os != 'Windows'
        run: bash scripts/e2e.sh
        env:
          GAMEMAKER_PAT: ${{ secrets.GAMEMAKER_PAT }}
          NO_COLOR: 1

      - name: E2E (PowerShell)
        if: runner.os == 'Windows'
        run: .\scripts\e2e.ps1
        env:
          GAMEMAKER_PAT: ${{ secrets.GAMEMAKER_PAT }}
          NO_COLOR: 1
