name: Package

on: [workflow_dispatch]

env:
  GAME_NAME: "mygame"
  # You can pin a particular version by replacing latest. E.g., @experimental/gm@1.0.2
  GM_COMMAND: "@experimental/gm@latest"
  # TODO: Remove when not needed
  GAMEMAKER_AUTH_TOKEN: ${{ secrets.GAMEMAKER_AUTH_TOKEN }}

jobs:
  compile:
    strategy:
      matrix:
        include:
          # TODO: Should this be a matrix or a job input?
          - runner: ubuntu-latest
            target: operagx
          # - runner: ubuntu-latest
          #   target: linux
          # - runner: ubuntu-latest
          #   target: windows
          # - runner: macos-latest
          #   target: mac
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        working-directory: ./test

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        with:
          # TODO: Remove test/ for the real thing
          path: test/.gmcache
          key: ${{ runner.os }}-gmcache-${{ matrix.target }}

      # TODO: Remove when CLI doesn't require this
      - name: Make prefabs dir
        run: |
          echo "GAMEMAKER_PREFABS=$(pwd)/.prefabs" >> $GITHUB_ENV
          mkdir .prefabs

      - run: npx "$GM_COMMAND" login "$GAMEMAKER_PAT"
        # TODO: When license is no longer required
        # if: ${{ secrets.GAMEMAKER_PAT != '' }}
        env:
          GAMEMAKER_PAT: ${{ secrets.GAMEMAKER_PAT }}

      - run: npx "$GM_COMMAND" package --target ${{ matrix.target }} --output ./package.zip
        env:
          NO_COLOR: 1

      - name: Create artifact name
        run: echo "ARTIFACT_NAME=${GAME_NAME}-${{ matrix.target }}-${GITHUB_SHA::7}.zip" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./test/package.zip
